spring:
  application:
    name: HIS

  thymeleaf:
    enabled: true
    cache: true
    encoding: UTF-8
    check-template: true
    check-template-location: true
    excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8080

baidu:
  map:
    ak: M5Z26KbY4becagikF51GPyZf0x0zlITw
    comprehension: 70